### ISSUE TITLE
冒号闪烁，应该只分秒之间的闪烁，时分之间的不必闪烁，会更好一些

### ISSUE THREAD

**Issue by myhalo** [NMTuan/timeNow#1]
冒号闪烁，应该只分秒之间的闪烁，时分之间的不必闪烁，会更好一些

**Comment by NMTuan** [comment]
在我印象中，闪烁是时分之间，同时不显示秒。
所以我默认启动闪烁的用户会把秒隐藏掉😀

**Comment by NMTuan** [comment]
931dbd5afd2b9eb88f6d47dc178f572394f6df05
